In [3]:
import numpy as np


a=[1,2,3,4,5]
b=np.array(a)
print(a, type(a))
print(b, type(b))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
b=np.arange(1,10,2)
print(b, type(b), b.shape)

[1 3 5 7 9] <class 'numpy.ndarray'> (5,)


In [7]:
a=[[1,2,3], [4,5,6]]
b=np.array(a)
print(b, b.shpae)

AttributeError: 'numpy.ndarray' object has no attribute 'shpae'

In [10]:
a=[1,2,3,4,5,6]
b=np.array(a).reshape(2,3);
c=np.array(a).reshape(3,2);
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [13]:
print(b[0])
print(b[1][1])
print(b[:,1])

[1 2 3]
5
[2 5]


In [24]:
print(a*4)
print(b*3)

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
[[ 3  6  9]
 [12 15 18]]


In [28]:
aa=[1,2,3,4]
bb=[5,6]
arr1=np.array(aa)
arr2=np.array(bb)
print(aa+bb)
print(arr1+3)
print(arr1-1)
print(arr1*2)
print(arr1/2)
print(arr1//2)
print(arr1%2)

[1, 2, 3, 4, 5, 6]
[4 5 6 7]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[1 0 1 0]


In [31]:
a1=[[1,1,1],[2,2,2],[3,3,3]]
a2=[1,2,3]

b1=np.array(a1)
b2=np.array(a2)

print(b1)
print(b2)

print(b1+b2)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[1 2 3]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [41]:
print(b1)
print(b1.sum())
print(np.sum(b1))
print(b1.sum(axis=1))

print("-------------")

print(np.mean(b1))
print(np.sqrt(b1))
print(np.max(b1))
print(np.min(b1))
print(np.log(b1))

[[1 1 1]
 [2 2 2]
 [3 3 3]]
18
18
[3 6 9]
-------------
2.0
[[1.         1.         1.        ]
 [1.41421356 1.41421356 1.41421356]
 [1.73205081 1.73205081 1.73205081]]
3
1
[[0.         0.         0.        ]
 [0.69314718 0.69314718 0.69314718]
 [1.09861229 1.09861229 1.09861229]]


In [47]:
arr1 = [[3,4,5],[1,2,5],[6,7,9]]
print(np.sort(arr1))
print(np.sort(arr1, axis=1))
print(np.sort(arr1, axis=0))
print(np.sort(arr1,axis=0)[::-1,::])
print(np.sort(arr1, axis=1)[::,::-1])



[[3 4 5]
 [1 2 5]
 [6 7 9]]
[[3 4 5]
 [1 2 5]
 [6 7 9]]
[[1 2 5]
 [3 4 5]
 [6 7 9]]
[[6 7 9]
 [3 4 5]
 [1 2 5]]
[[5 4 3]
 [5 2 1]
 [9 7 6]]


TypeError: '>=' not supported between instances of 'list' and 'int'

In [51]:

arr1 = np.array(arr1)
print(arr1)
print(arr1>=5)

[[3 4 5]
 [1 2 5]
 [6 7 9]]
[[False False  True]
 [False False  True]
 [ True  True  True]]


In [56]:
#0,1으로 변수 세팅하기
a1 = np.zeros(10)
a2 = np.ones([3,3])
#ones_like(변수) = 변수크기만큼 1로채워라
b1 = np.ones_like(a2) 
print(a1)
print(a2)
print(b1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
